---
- name: Get docker-ce repository GPG key
  apt_key:
    url: "{{ docker_machine_docker_repo_gpg_url }}"
    state: present
    
- name: Add docker-ce repository
  apt_repository:
    repo: "{{ docker_machine_docker_repo_url }}"
    state: present
    
- name: Update docker-ce
  apt:
    update_cache: yes
    cache_valid_time: 600
    name: "docker-ce{{ '=' + docker_machine_docker_ce_version if docker_machine_docker_ce_version != 'latest' else '' }}"
    state: present

- name: Update docker-ce-cli
  apt:
    update_cache: yes
    cache_valid_time: 600
    name: "docker-ce-cli{{ '=' + docker_machine_docker_ce_version if docker_machine_docker_ce_version != 'latest' else '' }}"
    state: present
